// Code generated by WARHORSE protoc-gen-go. DO NOT EDIT EXCEPET SERVER VERSION.
// source: user.proto

package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Gender 用户性别
type Gender int32

const (
	// Unknow 未知
	Gender_Unknow Gender = 0
	// Male 男
	Gender_Male Gender = 1
	// 女
	Gender_Female Gender = 2
)

var Gender_name = map[int32]string{
	0: "Unknow",
	1: "Male",
	2: "Female",
}
var Gender_value = map[string]int32{
	"Unknow": 0,
	"Male":   1,
	"Female": 2,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}
func (Gender) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func init() {
	proto.RegisterEnum("user.Gender", Gender_name, Gender_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for User service

type UserClient interface {
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

// Server API for User service

type UserServer interface {
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "user.proto",
}

func init() {}

var fileDescriptor2 = []byte{
	// 93 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0xb5, 0xb4, 0xb8, 0xd8, 0xdc, 0x53,
	0xf3, 0x52, 0x52, 0x8b, 0x84, 0xb8, 0xb8, 0xd8, 0x42, 0xf3, 0xb2, 0xf3, 0xf2, 0xcb, 0x05, 0x18,
	0x84, 0x38, 0xb8, 0x58, 0x7c, 0x13, 0x73, 0x52, 0x05, 0x18, 0x41, 0xa2, 0x6e, 0xa9, 0xb9, 0x20,
	0x36, 0x93, 0x11, 0x1b, 0x17, 0x4b, 0x68, 0x71, 0x6a, 0x51, 0x12, 0x1b, 0xd8, 0x00, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x69, 0x65, 0xcd, 0xb9, 0x4e, 0x00, 0x00, 0x00,
}
